### ISSUE TITLE
use OrderedDict instead of dict

### ISSUE THREAD

**Issue by simnalamburt** [portone-io/gophplib#13]
PHP's associative array (dictionary) preserves insertion order unlike go's dict. Existing PHP codes can rely on this behavior. Thus, gophplib must support OrderedDict input as well as dict, and gophplib's return types must use OrderedDict instead of dict to support existing PHP codebases' associative array usecases.

### TODOs
- [ ] Choose OrderedDict library
- [ ] Add OrderedDict support to https://github.com/portone-io/gophplib/pull/12
- [ ] Change return type of `parse_str` and bump to v2.0.0

**Comment by simnalamburt** [comment]
OrderedDict
- https://github.com/wk8/go-ordered-map
- https://github.com/elliotchance/orderedmap
- ?

**Comment by moonjihae** [comment]
We conducted benchmark tests to compare the performance between the 'gods' library's orderedDict and the 'elliotchance/orderedmap'. Using the implode function from gophplib, we found that the implementation provided by 'elliotchance/orderedmap' was 37.3% faster compared to the 'gods' library. 
Based on these results, we have opted to use the 'elliotchance/orderedmap' library into gophplib. Details of the usage and benchmark tests for both libraries can be found in the commit linked below.
* [benchmark test for `gods` ](https://github.com/portone-io/gophplib/commit/ecb917ff9cbbc7e296197390d069d35ebe0a8426)
* [benchmark test for `elliotchance/orderedmap`](https://github.com/portone-io/gophplib/commit/1d7627568eec107418b880a4fd1a62bf3ad02d32)
